---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: standard-build-config
  namespace: infra-pipeline
parameters:
  - name: NAME
    description: >-
      Image name. Image will be published to image-registry.openshift-image-registry.svc:5000/infra/${NAME}:${TAG}
    required: true
  - name: TAG
    description: Image tag
  - name: DESCRIPTION
    description: Sets the description label on the image
  - name: DOCKERFILE_PATH
    displayName: Dockerfile path
    description: Path in the git repository of the Dockerfile to use for the build
    value: Containerfile
  - name: LIMIT_CPU
    description: Max cpu that the build can use
    value: "1"
  - name: LIMIT_MEMORY
    description: Max memory that the build can use
    value: 1G
  - name: IMAGE_OPTIMIZATION_POLICY
    description: >-
      SkipLayers or None. SkipLayers will squash all layers resulting in a smaller final image size.
    value: SkipLayers
objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: ${NAME}
    spec:
      runPolicy: Serial
      failedBuildsHistoryLimit: 1
      successfulBuildHistoryLimit: 1
      resources:
        limits:
          cpu: ${{LIMIT_CPU}}
          memory: ${{LIMIT_MEMORY}}
        requests:
          cpu: .100
          memory: 50Mi
      output:
        imageLabels:
          - name: description
            value: ${DESCRIPTION}
        to:
          kind: DockerImage
          name: image-registry.openshift-image-registry.svc:5000/infra/${NAME}:${TAG}
        pushSecret:
          name: images-push-config
      source:
        type: Binary
      strategy:
        # see https://docs.openshift.com/container-platform/4.11/cicd/builds/build-strategies.html
        type: Docker
        dockerStrategy:
          dockerfilePath: ${DOCKERFILE_PATH}
          imageOptimizationPolicy: ${IMAGE_OPTIMIZATION_POLICY}

