---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: deploy
  namespace: webinar
parameters:
  - name: name
    displayName: Name
    description: Name of the application
    value: webinar-site
  - name: project
    displayName: Project
    description: OpenShift project name
  - name: image
    displayName: Image
    description: Docker image
  - name: hostname
    displayName: Hostname
    description: Hostname to use in the route
    required: true
objects:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: webinar-site
      namespace: ${project}
      labels:
        app: ${name}
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: ${name}
      template:
        metadata:
          labels:
            app: ${name}
        spec:
          containers:
            - name: ${name}
              image: ${image}
              ports:
                - containerPort: 8000
                  protocol: TCP
              resources:
                limits:
                  cpu: 500m
                  memory: 256Mi
                requests:
                  cpu: 200m
                  memory: 64Mi

  - apiVersion: v1
    kind: Service
    metadata:
      name: ${name}
      namespace: ${project}
      labels:
        app: ${name}
    spec:
      selector:
        app: ${name}
      ports:
        - port: 8080

  - apiVersion: v1
    kind: Route
    metadata:
      name: ${name}
      namespace: ${project}
      labels:
        app: ${name}
    spec:
      host: ${hostname}
      port:
        targetPort: 8080
      to:
        kind: Service
        name: ${name}
        weight: 100
      wildcardPolicy: None

