apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webinar-site
  name: webinar-site
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webinar-site
  template:
    metadata:
      labels:
        app: webinar-site
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            region: us-east-2
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/webinar-site
          imagePullPolicy: Always
          name: webinar-site
          ports:
            - containerPort: 8000
              protocol: TCP
          resources:
                limits:
                  cpu: 500m
                  memory: 256Mi
                requests:
                  cpu: 200m
                  memory: 64Mi
